services:
  api:
    container_name: PROD_api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    env_file:
      - src/api_service/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  bot:
    container_name: PROD_bot
    build:
      context: .
      dockerfile: Dockerfile
      target: bot
    env_file:
      - src/bot_service/.env

  postgres:
    container_name: PROD_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

  redis:
    container_name: PROD_redis
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"


volumes:
  postgres-data:
